/usr/share/spark-3.2/bin/spark-submit --queue infra --deploy-mode cluster --archives "/tmp/pyspark_py39_1.tar.gz#environment" --conf spark.pyspark.python=./environment/bin/python3 --conf spark.pyspark.driver.python=./environment/bin/python3 --conf spark.archives=/tmp/pyspark_py39_1.tar.gz#environment --conf spark.driver.extraClassPath=elasticsearch-spark-30_2.12-8.4.0.jar --conf spark.executor.extraClassPath=elasticsearch-spark-30_2.12-8.4.0.jar --jars hdfs://R2/projects/eda/hdfs/prod/elasticsearch-spark-30_2.12-8.4.0.jar Prophet_Forecasting_es.py

/usr/share/spark-3.2/bin/spark-submit --queue infra --deploy-mode cluster --archives "/tmp/pyspark_py39_1.tar.gz#environment" --conf spark.pyspark.python=./environment/bin/python3 --conf spark.pyspark.driver.python=./environment/bin/python3 --conf spark.archives=/tmp/pyspark_py39_1.tar.gz#environment --conf spark.driver.extraClassPath=elasticsearch-spark-30_2.12-8.4.0.jar --conf spark.executor.extraClassPath=elasticsearch-spark-30_2.12-8.4.0.jar --jars hdfs://R2/projects/eda/hdfs/prod/elasticsearch-spark-30_2.12-8.4.0.jar Prophet_Forecasting_es_1.py



/usr/share/spark-3.2/bin/spark-submit --queue infra --deploy-mode cluster --conf spark.executor.cores=2 --conf spark.executor.memory=10G --archives "/tmp/pyspark_py39_1.tar.gz#environment" --conf spark.pyspark.python=./environment/bin/python3 --conf spark.pyspark.driver.python=./environment/bin/python3 --conf spark.archives=/tmp/pyspark_py39_1.tar.gz#environment --conf spark.driver.extraClassPath=elasticsearch-spark-30_2.12-8.4.0.jar --conf spark.executor.extraClassPath=elasticsearch-spark-30_2.12-8.4.0.jar --conf spark.sql.shuffle.partitions=1000 --jars hdfs://R2/projects/eda/hdfs/prod/elasticsearch-spark-30_2.12-8.4.0.jar Prophet_Forecasting_es_2.py -metric kubernetes.container.memory.request.bytes -set state_container


/usr/share/spark-3.2/bin/spark-submit --queue infra --deploy-mode cluster --conf spark.executor.cores=2 --conf spark.executor.memory=10G --archives "/tmp/pyspark_py39_1.tar.gz#environment" --conf spark.pyspark.python=./environment/bin/python3 --conf spark.pyspark.driver.python=./environment/bin/python3 --conf spark.archives=/tmp/pyspark_py39_1.tar.gz#environment --conf spark.driver.extraClassPath=elasticsearch-spark-30_2.12-8.4.0.jar --conf spark.executor.extraClassPath=elasticsearch-spark-30_2.12-8.4.0.jar --conf spark.sql.shuffle.partitions=1000 --jars hdfs://R2/projects/eda/hdfs/prod/elasticsearch-spark-30_2.12-8.4.0.jar Prophet_Forecasting_readFile3.py -metric kubernetes_container_cpu_usage_nanocores -set pod -path hdfs:///projects/eda/hdfs/prod/druid_metrics/druid_cpu_metrics_all_ns.csv &
/usr/share/spark-3.2/bin/spark-submit --queue infra --deploy-mode cluster --conf spark.executor.cores=2 --conf spark.executor.memory=10G --archives "/tmp/pyspark_py39_1.tar.gz#environment" --conf spark.pyspark.python=./environment/bin/python3 --conf spark.pyspark.driver.python=./environment/bin/python3 --conf spark.archives=/tmp/pyspark_py39_1.tar.gz#environment --conf spark.driver.extraClassPath=elasticsearch-spark-30_2.12-8.4.0.jar --conf spark.executor.extraClassPath=elasticsearch-spark-30_2.12-8.4.0.jar --conf spark.sql.shuffle.partitions=1000 --jars hdfs://R2/projects/eda/hdfs/prod/elasticsearch-spark-30_2.12-8.4.0.jar Prophet_Forecasting_readFile3.py -metric kubernetes_container_memory_usage_bytes -set pod -path hdfs:///projects/eda/hdfs/prod/druid_metrics/druid_memory_metrics_all_ns.csv &
/usr/share/spark-3.2/bin/spark-submit --queue infra --deploy-mode cluster --conf spark.executor.cores=2 --conf spark.executor.memory=10G --archives "/tmp/pyspark_py39_1.tar.gz#environment" --conf spark.pyspark.python=./environment/bin/python3 --conf spark.pyspark.driver.python=./environment/bin/python3 --conf spark.archives=/tmp/pyspark_py39_1.tar.gz#environment --conf spark.driver.extraClassPath=elasticsearch-spark-30_2.12-8.4.0.jar --conf spark.executor.extraClassPath=elasticsearch-spark-30_2.12-8.4.0.jar --conf spark.sql.shuffle.partitions=1000 --jars hdfs://R2/projects/eda/hdfs/prod/elasticsearch-spark-30_2.12-8.4.0.jar Prophet_Forecasting_readFile3.py -metric kubernetes_volume_fs_used_pct -set pod -path hdfs:///projects/eda/hdfs/prod/druid_metrics/druid_volume_metrics_all_ns.csv &